### ISSUE TITLE
It doesn't seem to like useless commas at the end of the JSON

### ISSUE THREAD

**Issue by raincoats** [izabera/j#1]
Hi, first let me say, this is so cool and it makes me want to learn more bash.

I'm not really a JSON master so this may be 100% invalid JSON, but it seems not to work if I put a comma before the final `}`. example:

``` shell

$ ./j <<< '{"wow": true, "yes": ["woah", false, 1,2,3, true],}'
# no output

$ ./j <<< '{"wow": true, "yes": ["woah", false, 1,2,3, true]}'
{
  "wow": true,
  "yes": [
    "woah",
    false,
    1,
    2,
    3,
    true
  ]
}
```

**Comment by izabera** [comment]
That's invalid json.  You'll get the same result with any other parser

```
jq . <<< '{"wow": true, "yes": ["woah", false, 1,2,3, true],}'
parse error: Expected another key-value pair at line 1, column 51
```

(Ok it's not the _same_ result, jq prints a useful message, but anyway...)

**Comment by raincoats** [comment]
Ah, I'd thought so. Cheers.
